# railway.toml
[env]
# Railway will interpolate the real public URL here at build time
SQLX_DATABASE_URL = "${{Postgres.DATABASE_PUBLIC_URL}}"

[build]
builder      = "nixpacks"
buildCommand = """
bash -lc '\
  cargo install sqlx-cli --no-default-features --features postgres && \
  echo SQLX_DATABASE_URL is $SQLX_DATABASE_URL && \
  cargo sqlx prepare --workspace -- --lib && \
  cargo build --release\
'
"""