name: Deploy Vectra DEX to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create deployment package
      run: |
        # Create a clean deployment package with just the necessary files
        zip -r deploy.zip . \
          -x '*.git*' \
          -x '.github/*' \
          -x 'target/*' \
          -x '*.md' \
          -x '.env*'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: vectra-api
        environment_name: vectra-api-dev
        version_label: "v${{ github.run_number }}-${{ github.sha }}"
        region: us-east-1
        deployment_package: deploy.zip
        wait_for_environment_recovery: 300
