name: Build and Deploy Vectra DEX API

on:
  push:
    branches:
      - main

jobs:
  verify-sqlx-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLx CLI
        run: |
          cargo install sqlx-cli --no-default-features --features postgres,rustls
        
      - name: Verify SQLx cache is up-to-date
        run: |
          # This will fail if cache is outdated
          cargo sqlx prepare --check --workspace
        env:
          SQLX_OFFLINE: true
  build-and-deploy:
    # This job depends on the verify-sqlx-cache job to ensure the SQLx cache is up-to-date
    needs: verify-sqlx-cache
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build and push Docker image using Dockerfile
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vectra-api .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/vectra-api:latest

    # Create deployment package with only Dockerrun.aws.json
    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x '*.git*' -x 'target/*' -x '.github/*' -x 'Dockerfile'

    # Deploy to EB
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: vectra-api
        environment_name: vectra-api-prod
        version_label: "v${{ github.run_number }}-${{ github.sha }}"
        region: us-east-1
        deployment_package: deploy.zip